openapi: 3.0.0
info:
  title: To-Do List API
  description: API for managing tasks in a To-Do List application
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
paths:
  /tasks:
    get:
      summary: Retrieve all tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      description: The task ID
                    title:
                      type: string
                      description: The title of the task
                    description:
                      type: string
                      description: The description of the task
                    completed:
                      type: boolean
                      description: Task completion status
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: The title of the task
                description:
                  type: string
                  description: The description of the task
      responses:
        '201':
          description: Task created
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  completed:
                    type: boolean
  /tasks/{id}:
    put:
      summary: Update task completion status
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                completed:
                  type: boolean
                  description: The new completion status
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  completed:
                    type: boolean
  /tasks/{id}:
    delete:
      summary: Delete a task by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Task deleted
